package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("test\"asd\"\"dvewr\"")
    void generatedTest() {
        step("test https://qa.guru", () -> {
            // todo
        });

        step("some steps", () -> {
            // todo
        });

        step("asr\"fdwdv\"\"", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'https://qa.guru'", () ->
            open("https://qa.guru"));

        step("Checking that page title is 'QA.GURU'", () -> {
            String expectedTitle = "QA.GURU";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}